apiVersion: v1
kind: ServiceAccount
metadata:
  name: vkubelet
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vkubelet
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: vkubelet
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkubelet
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vkubelet
  replicas: 1
  template:
    metadata:
      labels:
        app: vkubelet
    spec:
      containers:
        - name: manager
          command:
            - manager
            - --client-kubeconfig=/etc/kubernetes/client/kubeconfig
            - --provider=kcp
            - --nodename=cluster1
          image: k8scloudplatform/vkubelet:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: clientconfig
              mountPath: /etc/kubernetes/client
              readOnly: true
      serviceAccountName: vkubelet
      volumes:
        - name: clientconfig
          secret:
            secretName: cluster1
