apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkubelet
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vkubelet
  replicas: 1
  template:
    metadata:
      labels:
        app: vkubelet
    spec:
      containers:
        - name: manager
          command:
            - manager
            - --kubeconfig=/etc/kubernetes/admin.conf
            - --client-kubeconfig=/etc/kubernetes/admin.conf
            - --provider=kcp
            - --nodename=cluster1
          image: k8scloudplatform/vkubelet:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
              readOnly: true
      volumes:
        - hostPath:
            path: /etc/kubernetes/admin.conf
            type: FileOrCreate
          name: kubeconfig
